all :
	gcc   -Wall -Wextra -Werror -g -lmlx -framework OpenGL -framework AppKit -D BUFFER_SIZE=60\
		  cub3d.c\
		  functions/configuration/ft_file.c\
		  functions/initialization/ft_initialize_config.c\
		  functions/initialization/ft_initialize_mlx.c\
		  functions/helper-functions/ft_strncmp.c\
		  functions/helper-functions/ft_split.c\
		  functions/configuration/ft_read_file.c\
		  functions/helper-functions/ft_sub.c\
		  functions/helper-functions/get_next_line/get_next_line.c\
		  functions/helper-functions/get_next_line/get_next_line_utils.c\
		  functions/configuration/ft_set_configuration.c\
		  functions/check-errors/ft_check_line_break.c\
		  functions/helper-functions/ft_nbr_split.c\
		  functions/helper-functions/ft_free.c\
		  functions/check-errors/ft_check_errors_r.c\
		  functions/configuration/ft_set_resolution.c\
		  functions/helper-functions/ft_is_number.c\
		  functions/helper-functions/ft_atoi.c


