all :
	gcc    -g -lmlx -framework OpenGL -framework AppKit -D BUFFER_SIZE=60\
		  cub3d.c\
		  functions/configuration/ft_file.c\
		  functions/initialization/ft_initialize_config.c\
		  functions/initialization/ft_initialize_mlx.c\
		  functions/helper-functions/ft_strncmp.c\
		  functions/helper-functions/ft_split.c\
		  functions/configuration/ft_read_file.c\
		  functions/helper-functions/ft_sub.c\
		  functions/helper-functions/get_next_line/get_next_line.c\
		  functions/helper-functions/get_next_line/get_next_line_utils.c\
		  functions/configuration/ft_set_configuration.c\
		  functions/check-errors/ft_check_line_break.c\
		  functions/helper-functions/ft_nbr_split.c\
		  functions/helper-functions/ft_free.c\
		  functions/helper-functions/ft_is_number.c\
		  functions/helper-functions/ft_atoi.c\
		  functions/helper-functions/ft_zeros.c\
		  functions/check-errors/ft_check_errors_r.c\
		  functions/check-errors/ft_check_errors_no.c\
		  functions/check-errors/ft_check_errors_c.c\
		  functions/check-errors/ft_check_errors_ea.c\
		  functions/check-errors/ft_check_errors_f.c\
		  functions/check-errors/ft_check_errors_s.c\
		  functions/check-errors/ft_check_errors_so.c\
		  functions/check-errors/ft_check_errors_we.c\
		  functions/configuration/ft_set_no.c\
		  functions/configuration/ft_set_so.c\
		  functions/configuration/ft_set_we.c\
		  functions/configuration/ft_set_ea.c\
		  functions/configuration/ft_set_s.c\
		  functions/configuration/ft_set_f.c\
		  functions/configuration/ft_set_c.c\
		  functions/configuration/ft_set_resolution.c\
		  functions/check-errors/ft_check_texture.c\
		  functions/check-errors/ft_check_variables.c\
		  functions/check-errors/ft_check_not_var.c\
		  functions/check-errors/ft_check_map.c\
		  functions/check-errors/ft_check_map_errors.c\
		  functions/configuration/ft_lists.c\
		  functions/configuration/ft_store_map_list.c\
		  functions/mlx-draw/ft_put_pixel_to_image.c\
		  functions/mlx-draw/ft_put_rectangle.c\
		  functions/mlx-draw/ft_put_map.c\
		  functions/helper-functions/ft_realloc.c\
		  functions/configuration/ft_set_array2d.c\
		  functions/mlx-draw/ft_put_player.c\
		  functions/initialization/ft_initialize_player.c\
		  functions/mlx-draw/ft_put_orientation.c\
		  functions/configuration/ft_deal_key.c\
		  functions/configuration/ft_move.c


		  


	


