all:
	gcc   -g -lmlx -framework OpenGL -framework AppKit -D BUFFER_SIZE=60\
		cub3d.c\
		functions/lists/ft_lstadd_back.c\
		functions/lists/ft_lstnew.c\
		functions/lists/ft_lstlast.c\
		functions/lists/ft_lst_size.c\
		functions/initialize/ft_initialize_config.c\
		functions/initialize/ft_initialize_mlx.c\
		functions/helper-functions/ft_atoi.c\
		functions/helper-functions/ft_check_nbr_splits.c\
		functions/helper-functions/ft_is_number.c\
		functions/helper-functions/ft_realloc.c\
		functions/helper-functions/ft_split.c\
		functions/helper-functions/ft_sub.c\
		functions/helper-functions/ft_strncmp.c\
		functions/mlx-draw/ft_put_pixel_to_image.c\
		functions/mlx-draw/ft_draw_rectangle.c\
		functions/mlx-draw/ft_display_map.c\
		functions/configuration/ft_set_configuration_resolution.c\
		functions/configuration/ft_set_configuration.c\
		functions/configuration/ft_read_file.c \
		functions/store/ft_store_map_array.c\
		functions/store/ft_store_map_list.c\
		functions/print/ft_print_map_2d.c\
		functions/print/ft_print_list.c\
		functions/helper-functions/get_next_line/get_next_line.c\
		functions/helper-functions/get_next_line/get_next_line_utils.c\
		functions/initialize/ft_initialize_player.c\
		functions/map-errors/ft_check_first_last_line.c\
		functions/map-errors/ft_check_middle_line.c\
		functions/mlx-draw/ft_display_player.c\
		functions/mlx-draw/ft_display_player_orientation.c




		
	

		
		 